documentation:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]
github-actions:
  - changed-files:
      - any-glob-to-any-file: [".github/workflows/**", ".github/actions/**"]
security:
  - changed-files:
      - any-glob-to-any-file: ["repo/templates/SECURITY.md", "code/**", ".github/workflows/dependency-review.yml", ".github/workflows/codeql.yml"]
