title: "[Show and tell] "
labels: [show-and-tell]
body:
  - type: textarea
    id: project
    attributes:
      label: What did you build?
    validations:
      required: true
  - type: textarea
    id: lessons
    attributes:
      label: What did you learn?
