local function read(path)
  local file = assert(io.open(path, "r"))
  local value = file:read("*a")
  file:close()
  return value
end

local ci = read(".github/workflows/ci.yml")
assert(ci:match("name: CI"))
assert(ci:match("name: CI Gate"))
assert(ci:match("name: Publication Decision"))
assert(ci:match("uses: %./%.github/workflows/release%.yml"))
assert(ci:match("rustup target add wasm32%-wasip1"))
assert(ci:match("source%-checks%.lua contracts"))
assert(ci:match("source%-checks%.lua rust"))
assert(ci:match("source%-checks%.lua automation"))
assert(ci:match("name: Package %(%${%{ matrix%.target %}%}%)"))
assert(ci:match("windows%-11%-arm"))
assert(ci:match("install%-qt%-action"))
assert(ci:match("Upload unsigned package"))

local greetings = read(".github/workflows/greetings.yml")
assert(greetings:match("name: First Interaction"))
assert(greetings:match("actions/github%-script@ed597411d8f924073f98dfc5c65a23a2325f34cd"))
assert(greetings:match("state: 'all'"))
assert(greetings:match("candidate%.user%?%.login === pullRequest%.user%.login"))

local publication = read(".github/workflows/release.yml")
assert(publication:match("name: Publication"))
assert(publication:match("workflow_call:"))
assert(not publication:match("workflow_dispatch:"))
assert(publication:match("channel: %[canary, beta, stable%]"))
assert(publication:match("owner: kero%-net"))
assert(publication:match("repositories: kero"))
assert(publication:match("environment: release"))
assert(publication:match("name: Sign package"))
assert(publication:match("KERO_SIGN_RELEASE=1"))
assert(publication:match("Download signed release packages"))
assert(publication:match("windows%-11%-arm"))

local record = read("releases/publication.json")
assert(record:match('"enabled"%s*:%s*true') or record:match('"enabled"%s*:%s*false'))
assert(record:match('"record"%s*:%s*"2026%.08%.1%-regular"'))

local pipeline = read(".github/pipeline.lua")
assert(pipeline:match("distribution/scripts/package%.lua"))
assert(not pipeline:lower():match("powershell"))

local presets = read("host/qt/CMakePresets.json")
for _, target in ipairs({ "windows-arm64", "windows-x64", "linux-x64", "macos-arm64" }) do
  assert(presets:find('"' .. target .. '"', 1, true))
end
local qt_cmake = read("host/qt/CMakeLists.txt")
assert(qt_cmake:match("stage/usr/bin/kero%-install"))
assert(qt_cmake:match("resources/kero%.desktop"))

local files = assert(io.popen("git ls-files '*.ps1'"))
assert(files:read("*a") == "", "PowerShell scripts must not be tracked")
files:close()

local local_distribution = read(".github/workflows/local-distribution.yml")
assert(local_distribution:match("Local distribution portable checks"))
assert(local_distribution:match("KERO_PORTABLE_WORKFLOW=1"))
assert(local_distribution:match("distribution/scripts/local%-run%.lua portable"))
assert(read(".actrc"):match("ubuntu%-latest=catthehacker/ubuntu:act%-latest"))
local tasks = read(".vscode/tasks.json")
assert(tasks:match("Kero: Validate Locally"))
assert(not tasks:match("Kero: Portable"))
local distribution = read("distribution/distribution.kst")
for _, target in ipairs({ "windows-arm64", "windows-x64", "linux-x64", "macos-arm64" }) do
  assert(distribution:find("target " .. target, 1, true))
end
assert(distribution:match("nativeHost windows%-arm64"))
assert(distribution:match("requiredEnvironment KERO_QT_PREFIX,KERO_CXX_COMPILER"))
assert(read("distribution/tests/run.lua"):match("distribution/tests/contract%.lua"))
local local_runner = read("distribution/scripts/local-run.lua")
assert(local_runner:match("source%-checks%.lua local"))
assert(local_runner:match("act workflow_dispatch %-W %.github/workflows/local%-distribution%.yml %-j portable"))
assert(local_runner:match("docker info"))
assert(local_runner:match("%.heap/distribution"))
