local runner = assert(io.open("distribution/scripts/local-run.lua", "rb")):read("*a")
for _, stage in ipairs({ "portable", "build", "verify", "test", "all", "propose", "status" }) do
  assert(runner:find(stage .. " = true", 1, true), "missing stage: " .. stage)
end
assert(runner:find('runtime_mode = "', 1, true))
assert(runner:find('build_mode = "', 1, true))
assert(runner:find('chosen == "emulated"', 1, true))
assert(runner:find("distribution.local.kst", 1, true))
assert(runner:find("propose requires native runtime evidence", 1, true))
assert(runner:find("Candidate manifest written", 1, true))
assert(runner:find("source-checks.lua local", 1, true))
assert(runner:find("docker info", 1, true))
assert(runner:find("workflow_dispatch -W .github/workflows/local-distribution.yml -j portable", 1, true))
assert(not runner:find("KERO_CI_REPOSITORY", 1, true))
assert(assert(io.open("distribution/scripts/adapter.lua", "rb")):read("*a"):find("QEMU adapter", 1, true))
assert(assert(io.open("distribution.local.kst.example", "rb")):read("*a"):find("adapter qemu", 1, true))
assert(assert(io.open("kero.cmd", "rb")):read("*a"):find("distribution\\actions\\kero.cmd", 1, true))
local wrapper = assert(io.open("distribution/actions/kero.cmd", "rb")):read("*a")
assert(wrapper:find("x86_64-w64-mingw32-clang++", 1, true))
local package = assert(io.open("distribution/scripts/package.lua", "rb")):read("*a")
assert(package:find('KERO_SIGN_RELEASE") == "1"', 1, true))
