set(CPACK_PACKAGE_NAME "KERO")
file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/../../src/crates/kero-cli/Cargo.toml"
  KERO_CLI_VERSION_LINE LIMIT_COUNT 1 REGEX "^version = \"[0-9]")
if(NOT KERO_CLI_VERSION_LINE)
  message(FATAL_ERROR "Could not read the KERO host version from src/crates/kero-cli/Cargo.toml")
endif()
string(REGEX REPLACE "^version = \"([^\"]+)\"$" "\\1" CPACK_PACKAGE_VERSION "${KERO_CLI_VERSION_LINE}")
target_compile_definitions(kero-app PRIVATE KERO_VERSION=\"${CPACK_PACKAGE_VERSION}\")
set(CPACK_PACKAGE_FILE_NAME "kero-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGE_DIRECTORY "${KERO_RELEASE_DIRECTORY}")

if(APPLE)
  set(CPACK_GENERATOR DragNDrop)
elseif(UNIX)
  set(CPACK_GENERATOR TGZ)
else()
  set(CPACK_GENERATOR ZIP)
endif()
include(CPack)

if(WIN32)
  include(KeroWindowsPackaging)
elseif(APPLE)
  include(KeroMacOSPackaging)
elseif(UNIX)
  include(KeroLinuxPackaging)
endif()
