set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)

set(KERO_QT_PREFIX "$ENV{KERO_QT_PREFIX}" CACHE PATH "Qt kit prefix")
set(QT_HOST_PATH "$ENV{KERO_QT_HOST_PATH}" CACHE PATH "Qt host kit prefix")
set(KERO_RUNTIME_DIR "$ENV{KERO_RUNTIME_DIR}" CACHE PATH "Compiler runtime directory")
set(KERO_DEPLOY_TOOL "$ENV{KERO_DEPLOY_TOOL}" CACHE FILEPATH "Qt deployment tool")
set(KERO_ICON "$ENV{KERO_ICON}" CACHE FILEPATH "Generated Windows icon")
set(KERO_WINDRES "$ENV{KERO_WINDRES}" CACHE FILEPATH "Windows resource compiler")
set(KERO_RELEASE_DIRECTORY "$ENV{KERO_RELEASE_DIRECTORY}" CACHE PATH "Release package output directory")
set(KERO_HOST "$ENV{KERO_HOST}" CACHE FILEPATH "Built KERO terminal host executable")

if(KERO_QT_PREFIX)
  list(PREPEND CMAKE_PREFIX_PATH "${KERO_QT_PREFIX}")
endif()

find_package(Qt6 6.8 REQUIRED COMPONENTS Network Widgets)

if(NOT DEFINED ENV{KERO_WASM} OR NOT EXISTS "$ENV{KERO_WASM}")
  message(FATAL_ERROR "KERO_WASM must name the freshly built portable core")
endif()
if(NOT KERO_HOST OR NOT EXISTS "${KERO_HOST}")
  message(FATAL_ERROR "KERO_HOST must name the freshly built terminal host executable")
endif()

if(WIN32)
  if(KERO_WINDRES)
    file(TO_CMAKE_PATH "${KERO_WINDRES}" KERO_WINDRES_CMAKE_PATH)
    set(CMAKE_RC_COMPILER "${KERO_WINDRES_CMAKE_PATH}")
  endif()
  enable_language(RC)
  if(NOT KERO_ICON OR NOT EXISTS "${KERO_ICON}")
    message(FATAL_ERROR "Windows packages require KERO_ICON")
  endif()
  if(NOT MSVC AND NOT KERO_WINDRES)
    message(FATAL_ERROR "LLVM/MinGW packages require KERO_WINDRES")
  endif()
  configure_file("${KERO_ICON}" "${CMAKE_CURRENT_BINARY_DIR}/kero-icon.ico" COPYONLY)
  set(KERO_ICON_PATH "kero-icon.ico")
  file(TO_CMAKE_PATH "${CMAKE_CURRENT_BINARY_DIR}" KERO_ICON_INCLUDE_DIRECTORY)
  set(CMAKE_RC_FLAGS "${CMAKE_RC_FLAGS} -I\"${KERO_ICON_INCLUDE_DIRECTORY}\"")
  configure_file("${CMAKE_CURRENT_SOURCE_DIR}/resources/kero.rc.in" "${CMAKE_CURRENT_BINARY_DIR}/kero.rc" @ONLY)
endif()
